# Model Parameters
IMAGE_SIZE: [224, 224, 3]  # MobileNetV2 input size
BATCH_SIZE: 16  
EPOCHS: 10
LEARNING_RATE: 0.01
CLASSES: 4  # Number of tumor classes (glioma, meningioma, notumor, pituitary)

# Base Model Parameters
INCLUDE_TOP: False
WEIGHTS: imagenet

# Data Augmentation
AUGMENTATION: True
